import Head from 'next/head';
import { useTheme } from 'styled-components';

export default function DefaultSEO() {
  const theme = useTheme();

  return (
    <Head>
      <title>Bruno Tenorio - Portfólio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="theme-color" content={theme.colors['grey-900']} />
      <meta name="msapplication-TileColor" content={theme.colors['grey-900']} />
      <meta name="msapplication-navbutton-color" content={theme.colors['grey-900']} />
      <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}