import Head from "next/head";
import Header from "src/sections/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bruno Tenorio - Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <Header />
        <main>
          <p>Main</p>
        </main>
        <footer >
          <p>Footer</p>
        </footer>
      </div>
    </>
  );
}
